version: '3.1'

services:
  node:
    image: 'sarrare/devops:v1.0'
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: express
    depends_on:
      - Mysql
    environment:
      - DB_URL=Mysql
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_DATABASENAME=db
      - DB_PORT=3306

  Mysql:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=db
